export default {
  project1: require('./group_business.jpg'),
  project2: require('./open-mac-with-code.jpg'),
  project3: require('./pear-programming.jpg'),
  project4: require('./half-closed-mac.jpg'),
  logo: {
    android_studio: require('./logo_android_studio.png'),
    angular: require('./logo_angular.png'),
    aws: require('./logo_aws.png'),
    java: require('./logo_java.png'),
    node: require('./logo_node.jpg'),
    php: require('./logo_php.png'),
    react: require('./logo_react.png'),
    facebook: require('./logo_facebook.png'),
    instagram: require('./logo_instagram.png'),
    twitter: require('./logo_twitter.png'),
    github: require('./logo_github.png'),
  },
  man_running_with_coin: require('./man_running_with_coin.svg'),
  man_sitting_on_coins: require('./man_sitting_on_coins.svg'),
  monitor: require('./monitor.svg'),
  telemarketing: require('./telemarketing.svg'),
};
